# log4j2 logging configuration.

rootLogger.level = WARN
rootLogger.appenderRef.console.ref = CONSOLE

appender.console.type = Console
appender.console.name = CONSOLE
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} [%t] (%c) %-5p %m%n
