# log4j2 logging dev configuration.

rootLogger.level = DEBUG
rootLogger.appenderRef.console.ref = CONSOLE
rootLogger.appenderRef.rolling.ref = ROLLINGFILE

appender.console.type = Console
appender.console.name = CONSOLE
appender.console.target = SYSTEM_ERR
appender.console.filter.threshold.type = ThresholdFilter
appender.console.filter.threshold.level = INFO
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} [%t] (%C:%L) %-5p %m%n

appender.rolling.type = RollingFile
appender.rolling.name = ROLLINGFILE
appender.rolling.filter.threshold.type = ThresholdFilter
appender.rolling.filter.threshold.level = DEBUG
appender.rolling.fileName = /tmp/secor_dev/logs/secor.log
appender.rolling.filePattern = /tmp/secor_dev/logs/secor.log.%i
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{ISO8601} [%t] (%C:%L) %-5p %m%n
appender.rolling.policies.type = Policies
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 20MB
appender.rolling.strategy.type = DefaultRolloverStrategy
appender.rolling.strategy.max = 50
